### ISSUE TITLE
sendlocation with locale dependant decimal separator (comma instead of point)

### ISSUE THREAD

**Issue by tueddy** [tinuzz/wp-plugin-trackserver#12]
Hi,

i'm currently testing trackserver and it looks fine & professional, congrats!
I have tested together with some mobile apps. For Android i use OSMand (works fine), for iOS i purchased SendLocation (64Bit).

The current position is submitted by this iOS app with german decimal separator, so instead of

lat: 53.0792962
lon: 8.8016937

the position is submitted with "," instead of "."

in TrackServer i get
lat: 53
lon: 8

OK i will try to contact the author but i wonder if it's possible to catch this on server side?
so this can be interpreted right:
www.server/sendlocation?lat=53,0792962?lon=8,8016937

see the comma here instead of point for the decimal separator..

Let me know if you would fix this,
thanks and best regards
Dirk

**Comment by tinuzz** [comment]
Hi,

I don't have an iOS device, so I can't really test anything related to SendLocation. Do you happen to know if the same behaviour applies to the altitude, speed and heading parameters?

Best regards,
Martijn.

**Comment by tinuzz** [comment]
I implemented a fix, but I didn't test it. Can you test the plugin as it it currently on Github and see if it works?

**Comment by tueddy** [comment]
Hi tinuzz,

that was quite fast, thanks!
I see the commit and updated the source. Unfortunatly this doesn't fix my issue. ?

I'll setup a local installation and log the exact sendlocation URL to see where exactly the problem is and report back here.

Best regards
Dirk

**Comment by tueddy** [comment]
Hi,

i've got the query-params now on my local webserver for iOS-App SendLocation (64Bit), german locale:

...?lat=53,08663223&lon=8,84512544&altitude=5,158721923&speed=0&heading=0&hacc=10&vacc=4&deviceid=22625D60-A3FD-40F8-8919-C3216699DE1E

This params get's cut to lat 53.0 / lon 8.0 in trackserver.
Hope you can reproduce it?
Best
Dirk

**Comment by tueddy** [comment]
OK, updating from github failed, now i have the latest version and GEO position is exact.
Thanks for the very fast fix!

Best regards
Dirk
